name: Build and Deploy to EC2
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: kong-gw
  REGISTRY_HOST: 3.110.117.88:5000 # Replace with your EC2 public IP and registry port
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Allow insecure registries.
        run:  |
          echo '{ "insecure-registries": ["'$REGISTRY_HOST'"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        
      # - name: Login to Docker registry
        # run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $REGISTRY_HOST -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      
      - name: Build Docker image
        run: |
          docker build -t $REGISTRY_HOST/$IMAGE_NAME:latest .
    
      - name: Push Docker image
        run: |
          docker push $REGISTRY_HOST/$IMAGE_NAME:latest
    
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host:  3.110.117.88
          username:  ${{ secrets.EC2_USER }}
          password:  ${{ secrets.PASSWORD }}
          port:  22
          timeout:  "120s"
          envs: REGISTRY_HOST,IMAGE_NAME
          script: |
            docker pull $REGISTRY_HOST/$IMAGE_NAME:latest
            docker stop $IMAGE_NAME || true
            docker rm $IMAGE_NAME || true
            docker run -d --name kong-gateway  -p 8000:8000 -p 8001:8001 --network host $REGISTRY_HOST/$IMAGE_NAME:latest
